Repository Yonava/magic-graphs, pull requests merged in 2025-04, with the labels that each got.

#427 feat: image shape based on rect, fixes #95
  client/public/1F639.png
  client/src/playground/shape/ShapePlayground.vue
  client/src/shapes/image/cache.ts
  client/src/shapes/image/draw.ts
  client/src/shapes/image/hitbox.ts
  client/src/shapes/image/index.ts
  client/src/shapes/image/text.ts
  client/src/shapes/index.ts
  client/src/shapes/types.ts
Labels: enhancement

#429 fix: add arrow back to transition matrix
  client/src/products/graph-sandbox/ui/GraphInfoMenu/TransitionMatrixLabel.vue
Labels: bug

#430 feat: add shortcut to open help menu
  client/src/ui/product/HelpMenu.vue
Labels: enhancement, polish
