Repository Yonava/magic-graphs, pull requests merged in 2025-03, with the labels that each got.

#395 refactor(magic-shapes): text input refactor to use textOnCanvas api
  client/src/shapes/text.ts
  client/src/shapes/textarea.ts
  client/src/shapes/useTextDimensionsOnCanvas.ts
Labels: bug, code cleanup, magic shapes

#396 feat(magic-shapes): add star shape
  client/src/playground/shape/ShapePlayground.vue
  client/src/shapes/index.ts
  client/src/shapes/star/draw.ts
  client/src/shapes/star/hitbox.ts
  client/src/shapes/star/index.ts
  client/src/shapes/types.ts
Labels: enhancement, magic shapes

#407 feat: add delete key as shortcut
  client/src/graphs/plugins/shortcut/index.ts
Labels: enhancement

#408 feat(product): add UI polish
  client/src/graphs/plugins/annotations/index.ts
  client/src/graphs/plugins/interactive/index.ts
  client/src/ui/product/GraphProduct.vue
Labels: enhancement, polish

#409 fix: undo bug
  client/src/graphs/plugins/annotations/index.ts
  client/src/graphs/plugins/history/index.ts
  client/src/utils/types.ts
Labels: bug, high priority

#411 feat(ui): add new badge component
  client/src/ui/core/NewBadge.vue
  client/src/ui/product/ZoomButtons.vue
Labels: magic ui, polish

#412 feat(product): generate graph centered on screen
  client/src/graphs/templates/helpers.ts
  client/src/ui/product/CommandPalette.vue
Labels: enhancement, product

#413 chore: fix some linting errors
  client/package.json
  client/src/graphs/buttons/GraphBtns.vue
  client/src/playground/graph/GraphPlayground.vue
  client/src/products/graph-sandbox/Main.vue
  client/src/products/graph-sandbox/ui/IslandMarkup.vue
  client/src/products/graph-sandbox/ui/MarkupMenu/InputColor.vue
  client/src/products/graph-sandbox/ui/MarkupMenu/InputSize.vue
  client/src/products/graph-sandbox/ui/TreeShapeMenu.vue
  client/src/products/graph-sandbox/ui/TreeShapeMenuSettings.vue
  client/src/products/search-visualizer/Main.vue
  client/src/products/search-visualizer/components/CodeEditor.vue
  client/src/ui/core/Popover.vue
Labels: code cleanup

#418 feat: help menu refactor and redesign
  .vscode/settings.json
  client/src/graphs/base/index.ts
  client/src/graphs/plugins/shortcut/index.ts
  client/src/types.ts
  client/src/ui/graph/GDialog.vue
  client/src/ui/product/CommandPalette.vue
  client/src/ui/product/GraphProduct.vue
  client/src/ui/product/HelpMenu.vue
  client/src/ui/product/help/HelpContent.vue
  client/src/ui/product/help/HelpLinks.vue
  client/src/ui/product/help/HelpSection.vue
  client/src/ui/product/help/HelpShortcutKey.vue
  client/src/ui/product/help/HelpShortcuts.vue
  client/src/ui/product/help/HelpVideos.vue
Labels: enhancement

#415 feat: add zoom scale by percent
  client/src/ui/product/ZoomButtons.vue
  client/src/utils/components/usePinchToZoom.ts
Labels: enhancement

#419 feat: add zoom keyboard shortcuts
  client/package-lock.json
  client/package.json
  client/src/graphs/plugins/shortcut/index.ts
  client/src/graphs/plugins/shortcut/types.ts
  client/src/graphs/plugins/shortcut/useShortcutPressed.test.ts
  client/src/graphs/plugins/shortcut/useShortcutPressed.ts
  client/src/graphs/settings/index.ts
  client/src/ui/product/CommandPalette.vue
  client/src/ui/product/ZoomButtons.vue
  client/src/utils/components/usePinchToZoom.ts
Labels: enhancement, code cleanup

#424 fix: history did not handle loading
  client/src/graphs/base/index.ts
  client/src/graphs/base/types.ts
  client/src/graphs/events/types.ts
  client/src/graphs/plugins/history/index.ts
  client/src/graphs/plugins/history/types.ts
  client/src/graphs/plugins/persistent/index.ts
Labels: bug, magic graphs

#425 fix: more shortcut changes
  client/src/graphs/plugins/shortcut/index.ts
  client/src/graphs/plugins/shortcut/types.ts
  client/src/ui/product/CommandPalette.vue
  client/src/ui/product/ZoomButtons.vue
  client/src/ui/product/help/HelpContent.vue
  client/src/ui/product/help/HelpShortcutKey.vue
  client/src/ui/product/help/HelpShortcuts.vue
  client/src/ui/product/help/HelpVideos.vue
  client/src/utils/components/usePinchToZoom.ts
Labels: code cleanup
